import "server-only";
import type { Collection, MediaCategorySlug, MediaFile, MediaItem, MediaKind, VideoTechnical, AudioTechnical, ImageVariant, Storyboard, VideoRendition } from "@/types/content";
import type { ContentSource } from "./source";
import { MEDIA_RECORDS } from "@/data/media";
import { COLLECTIONS as SAMPLE_COLLECTIONS } from "@/data/collections";
import { INFO_ENTRIES, INFO_SECTIONS } from "@/data/info";
import { TIMELINE } from "@/data/timeline";
import { SOURCE_BY_SLUG } from "@/data/sources";
import sampleJson from "@/data/generated/sample-assets.json";
import gtaviceJson from "@/data/generated/gtavice.json";
import trailersJson from "@/data/generated/trailers.json";
import { TRAILER_RECORDS } from "@/data/trailers";

/* ------------------------------------------------------------------ */
/* Sample video/audio (generated by scripts/generate-sample-assets)     */
/* ------------------------------------------------------------------ */
interface SampleEntry {
  kind: MediaKind;
  original: MediaFile;
  variants: ImageVariant[];
  blurDataUrl?: string;
  dominantColor?: string | null;
  poster?: { url: string; width: number; height: number; bytes?: number };
  video?: VideoTechnical;
  audio?: AudioTechnical;
  storyboard?: Storyboard;
  renditions?: VideoRendition[];
}
const samples = sampleJson as unknown as Record<string, SampleEntry>;

/** Official trailers streamed from their hosts (scripts/import-trailers.mjs). */
const trailers = trailersJson as unknown as Record<string, SampleEntry>;

/** Sample stand-ins superseded by the official trailers. */
const REPLACED_SAMPLES = new Set(["video-trailer-1-sample", "video-trailer-2-sample"]);

/* ------------------------------------------------------------------ */
/* Official images imported by scripts/import-gtavice.mjs               */
/* ------------------------------------------------------------------ */
interface ImportedItem {
  slug: string;
  title: string;
  category: MediaCategorySlug;
  source: string;
  datePublished: string;
  dateAdded: string;
  width: number;
  height: number;
  original: MediaFile;
  variants: ImageVariant[];
  dominantColor: string | null;
  characters: string[];
  locations: string[];
  via: string;
}
interface ImportedCollection {
  slug: string;
  title: string;
  kind: "release" | "curated";
  date: string | null;
  description: string;
  via: string;
  mediaSlugs: string[];
}
const imported = gtaviceJson as unknown as { items: ImportedItem[]; collections: ImportedCollection[] };

/** Friendlier public slugs for imported galleries; sample trailer videos join their release. */
const COLLECTION_ALIAS: Record<string, { slug: string; prepend?: string[]; timelineEventId?: string; cover?: string }> = {
  "trailer-2-screencaps": { slug: "trailer-2", prepend: ["gta-vi-trailer-2"], timelineEventId: "2025-05-06-trailer-2" },
  "trailer-1-screencaps": { slug: "trailer-1", prepend: ["gta-vi-trailer-1"], timelineEventId: "2023-12-04-trailer-1" },
  "official-screenshots-may-6-2025": { slug: "screenshots-may-2025", timelineEventId: "2025-05-06-website", cover: "gv-vice-city-01" },
  "official-artwork-may-6-2025": { slug: "artwork-may-2025", cover: "gv-jason-and-lucia-01-landscape" },
  "an-extended-look-screencaps": { slug: "extended-look", prepend: ["gta-vi-extended-look"], timelineEventId: "2026-08-27-extended-look" },
  "official-cover-art-reveal": { slug: "cover-art", timelineEventId: "2026-06-18-cover-art", cover: "gv-gta-6-official-cover-art-landscape" },
  "official-pre-order-artwork": { slug: "pre-order-artwork" },
  "official-pre-order-screenshots": { slug: "pre-order-screenshots" },
  "netflix-announcement-aug-6-2026": { slug: "netflix-announcement", timelineEventId: "2026-08-06-netflix" },
  "official-previews-screenshots-and-artwork": { slug: "previews" },
  "official-website-screengrabs": { slug: "website-screengrabs" },
  "soundtrack-artwork": { slug: "soundtrack-artwork" },
  "official-merchandise": { slug: "merchandise" },
};

function buildCollections(): Collection[] {
  const out: Collection[] = imported.collections.map((c) => {
    const alias = COLLECTION_ALIAS[c.slug] ?? { slug: c.slug };
    const mediaSlugs = [...(alias.prepend ?? []).filter((s) => trailers[s]), ...c.mediaSlugs];
    return {
      slug: alias.slug,
      title: c.title,
      kind: c.kind,
      date: c.date ?? undefined,
      description: c.description,
      coverSlug: alias.cover && c.mediaSlugs.includes(alias.cover) ? alias.cover : c.mediaSlugs[0],
      mediaSlugs,
      sources: [{ label: "GTAVice.net gallery", url: c.via }],
      timelineEventId: alias.timelineEventId,
    };
  });
  // Keep the sample audio set until official audio is archived.
  for (const c of SAMPLE_COLLECTIONS) if (c.slug === "audio") out.push(c);
  return out;
}

function buildMedia(collections: Collection[]): MediaItem[] {
  const memberships = new Map<string, string[]>();
  for (const c of collections) for (const m of c.mediaSlugs) memberships.set(m, [...(memberships.get(m) ?? []), c.slug]);

  const items: MediaItem[] = [];

  for (const i of imported.items) {
    const source = SOURCE_BY_SLUG[i.source] ?? { slug: i.source, label: i.source, origin: "other" as const };
    items.push({
      id: i.slug,
      slug: i.slug,
      title: i.title,
      kind: "image",
      category: i.category,
      description: `${i.title}. Official Grand Theft Auto VI image from Rockstar Games.`,
      alt: i.title,
      datePublished: i.datePublished,
      dateAdded: i.dateAdded,
      source,
      officialUrl: i.via,
      width: i.width,
      height: i.height,
      original: i.original,
      variants: i.variants,
      dominantColor: i.dominantColor,
      tags: [],
      characters: i.characters,
      locations: i.locations,
      collections: memberships.get(i.slug) ?? [],
      downloadable: true,
      credit: "Rockstar Games",
      verification: "official",
    });
  }

  // Official trailers, then the remaining sample video/audio (galleries hold no audio).
  const timed = [
    ...TRAILER_RECORDS.map((r) => [r, trailers[r.slug]] as const),
    ...MEDIA_RECORDS.filter((r) => !REPLACED_SAMPLES.has(r.slug)).map((r) => [r, samples[r.slug]] as const),
  ];
  for (const [r, asset] of timed) {
    if (!asset || asset.kind === "image") continue;
    const source = SOURCE_BY_SLUG[r.source] ?? { slug: r.source, label: r.source, origin: "other" as const };
    items.push({
      id: r.slug,
      slug: r.slug,
      title: r.title,
      kind: asset.kind,
      category: r.category,
      description: r.description,
      alt: r.alt,
      datePublished: r.datePublished,
      dateAdded: r.dateAdded,
      source,
      officialUrl: r.officialUrl,
      width: asset.kind === "audio" ? undefined : (asset.original.width ?? asset.poster?.width),
      height: asset.kind === "audio" ? undefined : (asset.original.height ?? asset.poster?.height),
      original: asset.original,
      variants: asset.variants,
      poster: asset.poster
        ? { url: asset.poster.url, width: asset.poster.width, height: asset.poster.height, bytes: asset.poster.bytes, mimeType: "image/jpeg", filename: "poster.jpg" }
        : undefined,
      blurDataUrl: asset.blurDataUrl,
      dominantColor: asset.dominantColor ?? null,
      video: asset.video,
      audio: asset.audio,
      storyboard: asset.storyboard,
      renditions: asset.renditions,
      tags: r.tags,
      characters: r.characters,
      locations: r.locations,
      collections: memberships.get(r.slug) ?? [],
      downloadable: r.downloadable,
      credit: r.credit,
      verification: r.verification,
    });
  }
  return items;
}

let cache: { media: MediaItem[]; collections: Collection[]; bySlug: Map<string, MediaItem> } | null = null;
function data() {
  if (!cache) {
    const collections = buildCollections();
    const media = buildMedia(collections);
    cache = { media, collections, bySlug: new Map(media.map((m) => [m.slug, m])) };
  }
  return cache;
}

export const localSource: ContentSource = {
  async listMedia() {
    return data().media;
  },
  async getMedia(slug) {
    return data().bySlug.get(slug) ?? null;
  },
  async listCollections() {
    return data().collections;
  },
  async getCollection(slug) {
    return data().collections.find((c) => c.slug === slug) ?? null;
  },
  async listInfoSections() {
    return [...INFO_SECTIONS].sort((a, b) => a.order - b.order);
  },
  async listInfoEntries(section) {
    return section ? INFO_ENTRIES.filter((e) => e.section === section) : INFO_ENTRIES;
  },
  async getInfoEntry(section, slug) {
    return INFO_ENTRIES.find((e) => e.section === section && e.slug === slug) ?? null;
  },
  async listTimeline() {
    return [...TIMELINE].sort((a, b) => a.date.localeCompare(b.date));
  },
};
